name: "Publish Release"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Cho phép bạn bấm nút build thủ công bất cứ lúc nào

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest" # Chỉ định chạy trên server Windows của GitHub

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: install frontend dependencies
        run: npm install # Hoặc yarn install / pnpm install tùy dự án

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # Tự động tạo phiên bản dựa trên package.json
          releaseName: "Trauso App v__VERSION__"
          releaseBody: "File build tự động từ GitHub Actions"
          releaseDraft: true
          prerelease: false
